2018-01-03 09:42:36 TRACE - main thread starts
2018-01-03 09:42:36 TRACE - service constructor invoked
2018-01-03 09:42:36 TRACE - static block called in dao
2018-01-03 09:42:36 DEBUG - HashMap initialized with 3 account instances
2018-01-03 09:42:36 TRACE - setter setDao() invoked
2018-01-03 09:42:36 DEBUG - injecting dao
2018-01-03 09:42:36 INFO - service instance is           
2018-01-03 09:42:36 DEBUG - service instance created
2018-01-03 09:42:36 INFO - transfer the amount Rs.5000 from Acc1001 to Acc1002
2018-01-03 09:42:36 TRACE - transferfund() invoked in service
2018-01-03 09:42:36 TRACE - getAccount() method invoked
2018-01-03 09:42:36 DEBUG - checking the eid against map key 
2018-01-03 09:42:36 INFO - account ID 1001 found
2018-01-03 09:42:36 DEBUG - From account retrieved
2018-01-03 09:42:36 TRACE - getAccount() method invoked
2018-01-03 09:42:36 DEBUG - checking the eid against map key 
2018-01-03 09:42:36 ERROR - No ID Found
com.sapient.exceptions.IdException: No ID Found
	at com.sapient.dao.DaoImpl.getAccount(DaoImpl.java:33)
	at com.sapient.service.SerImpl.transferFund(SerImpl.java:38)
	at com.sapient.client.TransferClient.main(TransferClient.java:24)
2018-01-03 09:42:36 INFO - transfer the amount Rs.500 from Acc1003 to Acc1002
2018-01-03 09:42:36 TRACE - transferfund() invoked in service
2018-01-03 09:42:36 TRACE - getAccount() method invoked
2018-01-03 09:42:36 DEBUG - checking the eid against map key 
2018-01-03 09:42:36 ERROR - No ID Found
com.sapient.exceptions.IdException: No ID Found
	at com.sapient.dao.DaoImpl.getAccount(DaoImpl.java:33)
	at com.sapient.service.SerImpl.transferFund(SerImpl.java:35)
	at com.sapient.client.TransferClient.main(TransferClient.java:32)
2018-01-03 09:42:36 INFO - transfer the amount Rs.500 from Acc2003 to Acc1002
2018-01-03 09:42:36 TRACE - transferfund() invoked in service
2018-01-03 09:42:36 TRACE - getAccount() method invoked
2018-01-03 09:42:36 DEBUG - checking the eid against map key 
2018-01-03 09:42:36 ERROR - No ID Found
com.sapient.exceptions.IdException: No ID Found
	at com.sapient.dao.DaoImpl.getAccount(DaoImpl.java:33)
	at com.sapient.service.SerImpl.transferFund(SerImpl.java:35)
	at com.sapient.client.TransferClient.main(TransferClient.java:40)
2018-01-03 09:43:41 TRACE - main thread starts
2018-01-03 09:43:41 TRACE - service constructor invoked
2018-01-03 09:43:41 TRACE - static block called in dao
2018-01-03 09:43:41 DEBUG - HashMap initialized with 3 account instances
2018-01-03 09:43:41 TRACE - setter setDao() invoked
2018-01-03 09:43:41 DEBUG - injecting dao
2018-01-03 09:43:41 INFO - service instance is           
2018-01-03 09:43:41 DEBUG - service instance created
2018-01-03 09:43:41 INFO - transfer the amount Rs.5000 from Acc1001 to Acc1002
2018-01-03 09:43:41 TRACE - transferfund() invoked in service
2018-01-03 09:43:41 TRACE - getAccount() method invoked
2018-01-03 09:43:41 DEBUG - checking the eid against map key 
2018-01-03 09:43:41 INFO - account ID 1001 found
2018-01-03 09:43:41 DEBUG - From account retrieved
2018-01-03 09:43:41 TRACE - getAccount() method invoked
